// <auto-generated />
using System;
using AscentService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AscentService.Infrastructure.Migrations
{
    [DbContext(typeof(AscentDbContext))]
    partial class AscentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AscentService.Domain.Ascents.Ascent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AscentDate")
                        .HasColumnType("date")
                        .HasColumnName("ascent_date");

                    b.Property<Guid?>("ClientAscentId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_ascent_id");

                    b.Property<string>("Companions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("companions");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("RouteNotes")
                        .HasColumnType("text")
                        .HasColumnName("route_notes");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Public")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "AscentDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_ascents_user_date");

                    b.HasIndex("UserId", "ClientAscentId")
                        .IsUnique()
                        .HasDatabaseName("ux_ascents_user_client_id")
                        .HasFilter("client_ascent_id IS NOT NULL");

                    b.ToTable("ascents", (string)null);
                });

            modelBuilder.Entity("AscentService.Domain.ConfirmedUsers.ConfirmedUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.ToTable("confirmed_users", (string)null);
                });

            modelBuilder.Entity("AscentService.Domain.DeletedUsers.DeletedUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.ToTable("deleted_users", (string)null);
                });

            modelBuilder.Entity("Common.Infrastructure.Persistence.Idempotency.ProcessedMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("MessageId");

                    b.ToTable("processed_messages", (string)null);
                });

            modelBuilder.Entity("Common.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "NextAttemptAtUtc")
                        .HasDatabaseName("ix_outbox_messages_processed_at_utc");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("AscentService.Domain.Ascents.Ascent", b =>
                {
                    b.OwnsOne("AscentService.Domain.Ascents.AscentConditions", "Conditions", b1 =>
                        {
                            b1.Property<Guid>("AscentId");

                            b1.Property<int?>("Snow");

                            b1.Property<int?>("Trail");

                            b1.Property<int?>("Wind");

                            b1.HasKey("AscentId");

                            b1.ToTable("ascents");

                            b1
                                .ToJson("conditions")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AscentId");
                        });

                    b.OwnsOne("AscentService.Domain.Ascents.PeakSnapshot", "Peak", b1 =>
                        {
                            b1.Property<Guid>("AscentId")
                                .HasColumnType("uuid");

                            b1.Property<int>("AltitudeMeters")
                                .HasColumnType("integer")
                                .HasColumnName("peak_altitude_m");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("peak_name");

                            b1.Property<Guid>("PeakId")
                                .HasColumnType("uuid")
                                .HasColumnName("peak_id");

                            b1.HasKey("AscentId");

                            b1.HasIndex("PeakId")
                                .HasDatabaseName("ix_ascents_peak");

                            b1.ToTable("ascents");

                            b1.WithOwner()
                                .HasForeignKey("AscentId");
                        });

                    b.OwnsMany("AscentService.Domain.Ascents.AscentPhoto", "Photos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("CloudinaryPublicId")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("cloudinary_public_id");

                            b1.Property<int>("Height")
                                .HasColumnType("integer")
                                .HasColumnName("height");

                            b1.Property<short>("Position")
                                .HasColumnType("smallint")
                                .HasColumnName("position");

                            b1.Property<DateTime>("UploadedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("uploaded_at_utc");

                            b1.Property<int>("Width")
                                .HasColumnType("integer")
                                .HasColumnName("width");

                            b1.Property<Guid>("ascent_id")
                                .HasColumnType("uuid")
                                .HasColumnName("ascent_id");

                            b1.HasKey("Id");

                            b1.HasIndex("ascent_id", "Position")
                                .IsUnique()
                                .HasDatabaseName("ux_ascent_photo_position");

                            b1.ToTable("ascent_photos", null, t =>
                                {
                                    t.HasCheckConstraint("ck_ascent_photo_position", "position BETWEEN 0 AND 2");
                                });

                            b1.WithOwner()
                                .HasForeignKey("ascent_id");
                        });

                    b.Navigation("Conditions")
                        .IsRequired();

                    b.Navigation("Peak")
                        .IsRequired();

                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
